#!/usr/bin/env node
/**
 * add-cve.mjs - Fetch CVE info from NVD and generate a vulnerability entry template
 *
 * Usage: node scripts/add-cve.mjs CVE-2024-XXXXX
 *
 * Outputs a TypeScript snippet ready to paste into src/vulnerabilities.ts
 */

const CVE_ID = process.argv[2];

if (!CVE_ID || !/^CVE-\d{4}-\d{4,}$/.test(CVE_ID)) {
  console.error('Usage: node scripts/add-cve.mjs CVE-YYYY-NNNNN');
  process.exit(1);
}

// Known VPN vendors for matching
const VPN_VENDORS = {
  fortinet: ['fortinet', 'fortigate', 'fortios'],
  paloalto: ['palo alto', 'pan-os', 'globalprotect'],
  cisco: ['cisco', 'asa', 'firepower', 'anyconnect'],
  checkpoint: ['check point', 'checkpoint'],
  f5: ['f5', 'big-ip', 'bigip'],
  juniper: ['juniper', 'junos', 'srx'],
  pulse: ['pulse secure', 'pulse connect'],
  ivanti: ['ivanti', 'connect secure', 'policy secure'],
  citrix: ['citrix', 'netscaler', 'adc'],
  sonicwall: ['sonicwall', 'sma', 'sonic wall'],
  sophos: ['sophos'],
  watchguard: ['watchguard'],
  barracuda: ['barracuda'],
  zyxel: ['zyxel'],
  array: ['array networks', 'arrayos'],
  draytek: ['draytek', 'vigor'],
  mikrotik: ['mikrotik', 'routeros'],
  openvpn: ['openvpn'],
  wireguard: ['wireguard'],
};

async function fetchJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} from ${url}`);
  return res.json();
}

function mapSeverity(baseSeverity) {
  const s = (baseSeverity || '').toUpperCase();
  if (s === 'CRITICAL') return 'critical';
  if (s === 'HIGH') return 'high';
  if (s === 'MEDIUM') return 'medium';
  return 'low';
}

function detectVendor(description) {
  const lower = description.toLowerCase();
  for (const [vendor, keywords] of Object.entries(VPN_VENDORS)) {
    for (const kw of keywords) {
      if (lower.includes(kw)) return vendor;
    }
  }
  return 'unknown';
}

async function main() {
  // 1. Fetch from NVD
  console.error(`Fetching ${CVE_ID} from NVD...`);
  const nvdData = await fetchJSON(
    `https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=${CVE_ID}`
  );

  const vuln = nvdData.vulnerabilities?.[0]?.cve;
  if (!vuln) {
    console.error(`CVE ${CVE_ID} not found in NVD`);
    process.exit(1);
  }

  // Extract CVSS
  let cvss = null;
  let severity = 'high';
  const metrics = vuln.metrics || {};
  const cvss31 = metrics.cvssMetricV31?.[0]?.cvssData;
  const cvss40 = metrics.cvssMetricV40?.[0]?.cvssData;
  const cvss2 = metrics.cvssMetricV2?.[0]?.cvssData;
  const cvssData = cvss40 || cvss31 || cvss2;
  if (cvssData) {
    cvss = cvssData.baseScore;
    severity = mapSeverity(cvssData.baseSeverity || (cvss >= 9 ? 'CRITICAL' : cvss >= 7 ? 'HIGH' : cvss >= 4 ? 'MEDIUM' : 'LOW'));
  }

  // Description
  const description = vuln.descriptions?.find(d => d.lang === 'en')?.value || 'No description';

  // References
  const references = (vuln.references || [])
    .slice(0, 5)
    .map(r => r.url);
  // Always include NVD link
  const nvdLink = `https://nvd.nist.gov/vuln/detail/${CVE_ID}`;
  if (!references.includes(nvdLink)) references.push(nvdLink);

  // Detect vendor
  const vendor = detectVendor(description);

  // 2. Check CISA KEV
  console.error('Checking CISA KEV...');
  let cisaKev = false;
  try {
    const kevData = await fetchJSON(
      'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json'
    );
    cisaKev = kevData.vulnerabilities?.some(v => v.cveID === CVE_ID) || false;
  } catch (e) {
    console.error(`Warning: Could not fetch KEV list: ${e.message}`);
  }

  // 3. Output template
  const template = `  {
    cve: '${CVE_ID}',
    severity: '${severity}',
    cvss: ${cvss ?? 'undefined'},
    description: '${description.replace(/'/g, "\\'")}',
    affected: [
      { vendor: '${vendor}', product: 'TODO_PRODUCT', versionStart: 'TODO', versionEnd: 'TODO' },
    ],
    references: [
${references.map(r => `      '${r}',`).join('\n')}
    ],
    exploitAvailable: ${cisaKev}, // verify manually
    cisaKev: ${cisaKev},
  },`;

  console.log('\n// ---- Generated by add-cve.mjs ----');
  console.log(template);
  console.log('// ---- End generated ----\n');

  // Summary to stderr
  console.error(`\n✅ ${CVE_ID}`);
  console.error(`   Severity: ${severity} (CVSS: ${cvss ?? 'N/A'})`);
  console.error(`   Vendor:   ${vendor}`);
  console.error(`   CISA KEV: ${cisaKev}`);
  console.error(`   Description: ${description.substring(0, 100)}...`);
  console.error('\n⚠️  Review and fill in: product name, version ranges, exploitAvailable');
}

main().catch(e => {
  console.error(`Error: ${e.message}`);
  process.exit(1);
});
